# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 13:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_zhaiyao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='zhaiyao',
        ),
    ]
