# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 13:19
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20170729_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body_ckeditor',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='文章-ckeditor'),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(verbose_name='文章-Markdown'),
        ),
        migrations.AlterField(
            model_name='post',
            name='markdown_or_not',
            field=models.CharField(choices=[('m', 'markdown'), ('c', 'ckeditor')], default='c', max_length=6, verbose_name='编辑器选择'),
        ),
    ]
